_target_: models.sheaf_gnn.transductive.disc_models.DiscreteDiagSheafDiffusion
args:
  _target_: models.sheaf_gnn.config.SheafModelArguments
  dropout: 0.5
  hidden_channels: 128
  initial_dropout: 0.0
  input_dropout: 0.5
  # initial_dropout: 0.19820021933740484
  # input_dropout: 0.7640130970045499
  deg_normalised: True
  normalised: False
  layers: 8
  d: 3
  device: cuda
  sheaf_num_layers: 1
  sheaf_hidden_channels: 64
#edge_index:
sheaf_learner: '${sheaf_learner}'