_target_: models.sheaf_gnn.inductive.InductiveDiscreteDiagSheafDiffusion
args:
  _target_: models.sheaf_gnn.config.SheafModelArguments
  output_dim: 64
_edge_index: null
sheaf_learner: '${sheaf_learner}'